config/routes.rb
Rails.application.routes.draw do
  root to: 'import_commits#new'

  resources :commits, only: [:index] do
    delete 'remove_multiple', on: :collection
  end
  resources :import_commits, only:[:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/commit.rb
class Commit < ApplicationRecord
  validates :date, :user_id, :sha, :message, presence: true
  belongs_to :user

  paginates_per 10
end

app/models/import_commit.rb
class ImportCommit
  attr_reader :username, :repo, :email

  def initialize(username, repo, email)
    @username = username
    @repo = repo
    @email = email
  end

  def import_commits!
    clear_commits!
    begin
      data = data_from
    rescue StandardError => e
      case e.response.code
      when 404
        raise 'Wrong Name or Repository'
      when 403
        raise 'limit is Exceeded'
      end
    end
    create_data(data)
  end

  private
  def data_from
    n = 1; result = []
    while (request = JSON.parse(RestClient.get "https://api.github.com/repos/#{username}/#{repo}/commits?page=#{n}")).any?
      result += request
      n = n.next
    end
    result
  end

  def create_data(result)
    result.map! do |record|
      user = define_user_by(record)
      create_commit_for!(user, record)
    end
  end

  def define_user_by(record)
    User.find_or_create_by(email: record['commit']['author']['email']) do |user|
      user.name = record['commit']['author']['name']
    end
  end

  def create_commit_for!(user, record)
    user.commits.create(
        sha: record['sha'],
        date: record['commit']['author']['date'],
        message: record['commit']['message']
    )
  end

  def clear_commits!
    User.destroy_all
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, :email, presence: true
  has_many :commits, dependent: :destroy
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  protect_from_forgery with: :null_session
end

app/controllers/commits_controller.rb
class CommitsController < ApplicationController
  def index
    @commits = (@user ? @user.commits : Commit).order(:date).page params[:page]
    respond_with(@commits)
  end

  def remove_multiple
    ids = params[:commits_ids]
    Commit.where(id: ids).destroy_all
    respond_to do |format|
      format.html { redirect_to commits_url }
      format.js { render layout: false }
    end
  end
end

app/controllers/import_commits_controller.rb
class ImportCommitsController < ApplicationController

  def new
  end

  def create
    respond_with(get_commits) do |format|
      format.html { redirect_to commits_path }
    end
  rescue StandardError => e
    flash[:alert] = e.message
    render :new
  end

  private

  def get_commits
    ImportCommit.new(params[:user_name], params[:repository], params[:email]).import_commits!
  end

  def interpolation_options
    { resource_name: 'Request' }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/commits_helper.rb
module CommitsHelper
end

app/views/commits/_commit.html.slim
- @commits.each do |commit|
  tr
    td.col-lg-1.col-md-1.col-sm-1.col-xs-1.bord
      = check_box_tag 'commits_ids[]', commit.id
    td.col-lg-1.col-md-1.col-sm-1.col-xs-1.bord
      = commit.date.to_time.to_formatted_s(:long)
    td.col-lg-2.col-md-3.col-sm-3.col-xs-3.bord
      = commit.user.name
    td.col-lg-1.col-md-1.col-sm-1.col-xs-1.bord
      = commit.user.email
    td.col-lg-2.col-md-2.col-sm-2.col-xs-2.bord
      = commit.sha
    td.col-lg-4.col-md-4.col-sm-4.col-xs-5.bord
      = commit.message

app/views/commits/index.html.slim
.row
  .col-lg-12
    table.table.table-striped
      thead
        tr
          th.col-lg-1.col-md-1.col-sm-1.col-xs-1
            |Delete
          th.col-lg-1.col-md-1.col-sm-1.col-xs-1
            |Date:
          th.col-lg-2.col-md-3.col-sm-3.col-xs-3
            |Name:
          th.col-lg-1.col-md-1.col-sm-1.col-xs-1
            |Email:
          th.col-lg-2.col-md-2.col-sm-2.col-xs-2
            |Sha:
          th.col-lg-5.col-md-5.col-sm-5.col-xs-5
            |Message:
      tbody
        = form_tag remove_multiple_commits_path, method: :delete, class: 'remove-commits', remote: true
        = render 'commits/commit'
        = submit_tag 'Delete', class: 'btn-danger'

app/views/commits/remove_multiple.js.erb
$('.remove-commits').bind('ajax:success', function(){
    $(this).closest('tr').fadeOut();
})

app/views/common/_errors.html.slim
.col-lg-12.col-md-12.col-sm-12.col-xs-12-1alert.alert-danger.errors
  - resource.errors.full_messages.each do |message|
    = message
    button.close data-dismiss="alert"
      | x

app/views/import_commits/new.html.slim
.row
  .col-md-4.col-md-offset-3
    h3.text-info.text-center
    | Import Commits
= form_tag import_commits_path, method: :post do
  .form-group
    = text_field_tag :user_name, '', class: 'form-control', required: "required", placeholder: 'Enter Owner'
  .form-group
    = text_field_tag :repository, '', class: 'form-control', required: "required", placeholder: 'Enter Repository'
  .form-group
    = text_field_tag :email, '', class: 'form-control', required: "required", placeholder: "Enter Author's email"
  .text-right
    = submit_tag 'Import', class: 'btn btn-primary text-right'

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "ttask"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"

  body
    .container
      .row
        .col-md-5
          = bootstrap_flash
          = yield
          - if controller_name == 'commits'
            .text-center
              = paginate @commits, theme: 'twitter-bootstrap-3'